import "./globals.css";
import { Inter } from "next/font/google";
import "moment/locale/id";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <main className="container min-h-screen font-poppins">{children}</main>
        <footer className="flex justify-center mx-auto p-5 items-center text-2xl italic">
          <p className="bg-[#6790C9] p-2 rounded-md shadow-lg hover:bg-white text-white hover:text-black">Made by Ihsan Tri Marseno</p>
        </footer>
      </body>
    </html>
  );
}
